try:
    print (v)
except:
    print("error is handled")
